export const API_URL = 'https://forkify-api.herokuapp.com/api/v2/recipes/';
export const REQUEST_TIMEOUT_S = 10;
export const RESULTS_PER_PAGE = 10;
export const INITIAL_PAGE = 1;
export const INITIAL_TOTAL_PAGES = 1;
export const API_KEY = '80d2d969-420c-4728-8a3d-9dd5c1b50974';
export const SUCCESS_MODAL_S = 1250;
export const RECIPE_CACHE_KEY = 'recipe';
export const SEARCH_RESULTS_CACHE_KEY = 'searchResults';
export const CACHE_KEYS = new Set().add(RECIPE_CACHE_KEY).add(SEARCH_RESULTS_CACHE_KEY);
export const CACHE_CLEAR_INTERVAL = 86_400_000; // 1-day
